package com.sentrana.biq.datacontract

/**
 * data transfer object
 *
 * @constructor
 * @param token
 * @param securityCode
 * @param newPassword
 */
case class ChangeAutoGeneratedPassword(
  token:        String,
  securityCode: String,
  newPassword:  String
)
